import { CmsSnapshot, SiteContent } from "./types"

export const images = {
  hero: "https://images.unsplash.com/photo-1524069290683-0457abfe42c3?auto=format&fit=crop&w=2000&q=88",
  children:
    "https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=1400&q=84",
  classroom:
    "https://images.unsplash.com/photo-1572847748080-bac263fae977?auto=format&fit=crop&w=1400&q=84",
  community:
    "https://images.unsplash.com/photo-1707811180403-c22b7ef06476?auto=format&fit=crop&w=1400&q=84",
  woman:
    "https://images.unsplash.com/photo-1707811179851-c1f93698ad46?auto=format&fit=crop&w=1400&q=84",
  volunteers:
    "https://images.unsplash.com/photo-1667577113456-34c59803de33?auto=format&fit=crop&w=1400&q=84",
  group:
    "https://images.unsplash.com/photo-1692609659165-1ec4d8108c0e?auto=format&fit=crop&w=1400&q=84",
}

export const defaultSiteContent: SiteContent = {
  announcement: {
    enabled: false,
    label: "Current appeal",
    message:
      "A verified fundraising update can be published here from the admin dashboard.",
    link: { label: "Support the appeal", href: "/donate" },
    tone: "pink",
  },
  pageBanners: {
    news: {
      eyebrow: "News & updates",
      title: "What is happening at Samriddhi",
      body: "Verified announcements, organisation milestones and community updates from our team.",
      imageUrl: images.volunteers,
      imageAlt: "Community volunteers gathered together",
    },
    documents: {
      eyebrow: "Trust & governance",
      title: "Documents, shared openly",
      body: "View the foundation's incorporation, tax registration and governance records.",
      imageUrl: images.classroom,
      imageAlt: "Open books representing transparent records",
    },
    donate: {
      eyebrow: "Give with confidence",
      title: "Your support can create change",
      body: "Donate by verified QR, UPI or bank transfer. Share the transaction reference afterward so our team can verify it and issue an acknowledgement.",
      imageUrl: images.children,
      imageAlt: "Children together in a learning environment",
    },
    reports: {
      eyebrow: "Financial transparency",
      title: "Monthly & yearly reports",
      body: "Verified donation and utilisation reporting will be published here as records become available.",
      imageUrl: images.community,
      imageAlt: "Community members meeting together",
    },
  },
  about: {
    eyebrow: "Who we are",
    title: "Building hope. Creating opportunity. Serving communities.",
    lead: "Samriddhi Help Team Foundation is a Section 8 charitable organisation based in Hisar, Haryana.",
    body: "Our purpose is to turn compassion into responsible, community-focused action. We are building our work on trust, dignity, accountability and meaningful collaboration.",
    imageUrl: images.children,
    imageAlt: "Children sharing a moment together",
  },
  story: {
    eyebrow: "Our commitment",
    title: "Behind every number is a human story",
    lead: "We share authentic stories only when they are documented and approved—never invented, never reduced to a statistic.",
    body: "Samriddhi is committed to telling stories responsibly, protecting dignity and centering the voices of people and communities involved.",
    imageUrl: images.group,
    imageAlt: "A group of children sitting together",
  },
  focusAreas: [
    {
      id: "community-support",
      title: "Community support",
      summary:
        "Responsive support shaped by real needs, local context and respectful collaboration.",
      imageUrl: images.community,
      imageAlt: "Community members together outdoors",
      tone: "pink",
      enabled: true,
    },
    {
      id: "care-wellbeing",
      title: "Care & wellbeing",
      summary:
        "Compassion-led initiatives that protect dignity and strengthen individual and family wellbeing.",
      imageUrl: images.woman,
      imageAlt: "Woman caring for plants in a field",
      tone: "teal",
      enabled: true,
    },
    {
      id: "opportunity-inclusion",
      title: "Opportunity & inclusion",
      summary:
        "Helping create pathways to learning, participation and opportunity for underserved communities.",
      imageUrl: images.classroom,
      imageAlt: "Students in a classroom",
      tone: "yellow",
      enabled: true,
    },
  ],
  fundraising: {
    enabled: true,
    eyebrow: "Fund Raising",
    title: "Support a verified need",
    body: "Every appeal published here is managed by the foundation with a clear purpose, funding goal and verified progress.",
    campaigns: [],
  },
  impactMetrics: [
    {
      id: "people",
      label: "People reached",
      value: "—",
      note: "Awaiting verified data",
    },
    {
      id: "initiatives",
      label: "Initiatives",
      value: "—",
      note: "Awaiting verified data",
    },
    {
      id: "volunteers",
      label: "Volunteers",
      value: "—",
      note: "Awaiting verified data",
    },
    {
      id: "communities",
      label: "Communities",
      value: "—",
      note: "Awaiting verified data",
    },
  ],
  news: [
    {
      id: "csr-registration-2026",
      slug: "csr-registration-confirmed",
      title: "Foundation registered to undertake CSR activities",
      summary:
        "The Ministry of Corporate Affairs has registered Samriddhi Help Team Foundation for undertaking CSR activities.",
      body: "On 30 January 2026, the Registrar of Companies approved the foundation's CSR-1 registration. The assigned registration number is CSR00104011. The approval supports responsible collaboration with eligible organisations on aligned CSR initiatives.",
      imageUrl: images.volunteers,
      imageAlt: "People collaborating on a community initiative",
      category: "Governance",
      author: "Samriddhi Help Team Foundation",
      publishedAt: "2026-01-30",
      status: "published",
      featured: true,
    },
    {
      id: "tax-registrations-2025",
      slug: "12ab-80g-provisional-status",
      title: "12AB registration and 80G approval granted provisionally",
      summary:
        "The Income Tax Department granted provisional 12AB registration and 80G approval for AY 2026–27 through AY 2028–29.",
      body: "The foundation received its provisional registration under section 12A and provisional approval under section 80G on 5 November 2025. Both orders cover assessment years 2026–27 through 2028–29 and remain subject to the conditions described in the official orders available in our document centre.",
      imageUrl: images.classroom,
      imageAlt: "Documents arranged for review",
      category: "Compliance",
      author: "Samriddhi Help Team Foundation",
      publishedAt: "2025-11-05",
      status: "published",
      featured: false,
    },
    {
      id: "incorporation-2025",
      slug: "foundation-incorporated",
      title: "Samriddhi Help Team Foundation incorporated",
      summary:
        "The foundation was incorporated as a Section 8 company on 24 October 2025 in Haryana.",
      body: "Samriddhi Help Team Foundation was incorporated on 24 October 2025 under the Companies Act, 2013. The organisation is a company limited by shares with Corporate Identity Number U88900HR2025NPL137636 and Section 8 Licence Number 174891.",
      imageUrl: images.hero,
      imageAlt:
        "Children representing the communities the foundation aims to serve",
      category: "Organisation",
      author: "Samriddhi Help Team Foundation",
      publishedAt: "2025-10-24",
      status: "published",
      featured: false,
    },
  ],
  donation: {
    acceptingDonations: true,
    currency: "INR",
    minimumAmount: 100,
    qrImageUrl: "",
    upiId: "",
    payeeName: "Samriddhi Help Team Foundation",
    bankName: "",
    accountName: "Samriddhi Help Team Foundation",
    accountNumber: "",
    ifsc: "",
    branch: "",
    accountType: "Current account",
    instructions:
      "Use only the verified QR, UPI ID or bank information shown on this page. After payment, share your UTR or transaction reference with the foundation for verification and acknowledgement.",
    receiptEmail: "samriddhihelpteam@gmail.com",
    gatewayEnabled: false,
  },
  documents: [
    {
      id: "certificate-incorporation",
      title: "Certificate of Incorporation",
      category: "Incorporation",
      description:
        "Certificate issued by the Ministry of Corporate Affairs under sections 7 and 8 of the Companies Act, 2013.",
      reference: "CIN U88900HR2025NPL137636",
      issuedAt: "2025-10-24",
      validThrough: "Current",
      url: "documents/certificate-of-incorporation.pdf",
      fileType: "PDF",
      fileSize: "71 KB",
      isPublic: true,
      featured: true,
    },
    {
      id: "section-8-licence",
      title: "Section 8 Licence",
      category: "Incorporation",
      description:
        "Licence issued under section 8(1) of the Companies Act, 2013.",
      reference: "Licence No. 174891",
      issuedAt: "2025-10-24",
      validThrough: "Current",
      url: "documents/section-8-licence.pdf",
      fileType: "PDF",
      fileSize: "55 KB",
      isPublic: true,
      featured: true,
    },
    {
      id: "12ab-registration",
      title: "12AB Provisional Registration",
      category: "Tax registration",
      description:
        "Income Tax Department order granting provisional registration under section 12A.",
      reference: "URN ABRCS6665EE20251",
      issuedAt: "2025-11-05",
      validThrough: "AY 2028–29",
      url: "documents/12ab-provisional-registration.pdf",
      fileType: "PDF",
      fileSize: "55 KB",
      isPublic: true,
      featured: true,
    },
    {
      id: "80g-approval",
      title: "80G Provisional Approval",
      category: "Tax registration",
      description:
        "Income Tax Department order granting provisional approval under section 80G.",
      reference: "URN ABRCS6665EF20251",
      issuedAt: "2025-11-05",
      validThrough: "AY 2028–29",
      url: "documents/80g-provisional-approval.pdf",
      fileType: "PDF",
      fileSize: "54 KB",
      isPublic: true,
      featured: true,
    },
    {
      id: "csr-registration",
      title: "CSR-1 Registration Letter",
      category: "CSR",
      description:
        "MCA approval for registration of the entity for undertaking CSR activities.",
      reference: "CSR00104011",
      issuedAt: "2026-01-30",
      validThrough: "Current",
      url: "documents/csr-registration-letter.pdf",
      fileType: "PDF",
      fileSize: "70 KB",
      isPublic: true,
      featured: true,
    },
    {
      id: "articles-association",
      title: "Articles of Association",
      category: "Governance",
      description:
        "The foundation's registered e-Articles of Association (Form INC-31).",
      reference: "Form INC-31",
      issuedAt: "2025-10-18",
      validThrough: "Current",
      url: "documents/articles-of-association.pdf",
      fileType: "PDF",
      fileSize: "223 KB",
      isPublic: true,
      featured: false,
    },
    {
      id: "tan-allotment",
      title: "TAN Allotment Letter",
      category: "Tax identity",
      description:
        "Income Tax Department letter allotting the foundation's Tax Deduction and Collection Account Number.",
      reference: "TAN RTKS52433D",
      issuedAt: "2025-10-24",
      validThrough: "Current",
      url: "documents/tan-allotment-letter.jpeg",
      fileType: "JPEG",
      fileSize: "206 KB",
      isPublic: true,
      featured: false,
    },
    {
      id: "pan-card",
      title: "e-PAN Card",
      category: "Tax identity",
      description:
        "Electronic Permanent Account Number card issued to the foundation.",
      reference: "PAN ABRCS6665E",
      issuedAt: "2025-10-24",
      validThrough: "Current",
      url: "documents/pan-card.jpeg",
      fileType: "JPEG",
      fileSize: "158 KB",
      isPublic: true,
      featured: false,
    },
    // Added to the live database by backend migration 005_npo_darpan_documents.sql.
    {
      id: "npo-darpan-registration",
      title: "NPO Darpan Registration Profile",
      category: "NPO Darpan",
      description:
        "The foundation's profile on NITI Aayog's NPO Darpan portal, showing its Darpan ID, registration details, office bearers, working area and achievements.",
      reference: "Darpan ID HR/2025/0863511",
      issuedAt: "2025-10-28",
      validThrough: "Current",
      url: "documents/npo-darpan-registration-profile.pdf",
      fileType: "PDF",
      fileSize: "947 KB",
      isPublic: true,
      featured: false,
    },
    {
      id: "npo-darpan-affidavit",
      title: "NPO Darpan Affidavit",
      category: "NPO Darpan",
      description:
        "Affidavit submitted to NITI Aayog for NPO Darpan registration, confirming the foundation's particulars and its office bearers and key functionaries.",
      reference: "Declared by Jagbir Singh, President",
      issuedAt: "2025-10-28",
      validThrough: "Current",
      url: "documents/npo-darpan-affidavit.pdf",
      fileType: "PDF",
      fileSize: "579 KB",
      isPublic: true,
      featured: false,
    },
  ],
  reports: [],
  contact: {
    email: "samriddhihelpteam@gmail.com",
    phone: "+91 88140 92008",
    whatsapp: "918814092008",
    address:
      "H.No. 01, Second Floor, VPO Kuleri, Hisar, Haryana – 125047, India",
    shortAddress: "Hisar, Haryana, India",
  },
}

export function createDefaultSnapshot(): CmsSnapshot {
  return {
    schemaVersion: 2,
    updatedAt: new Date().toISOString(),
    content: structuredClone(defaultSiteContent),
  }
}
